version: '3'
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rif"
    ports:
      - "5432:5432"
    volumes:
      - "./dbData:/var/lib/pgsql/data"