version: '3'
services:
  db:
    image:  mysql:5.7
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "3306:3306"
    volumes:
      - ./dbData:/var/lib/mysql