version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rif
    ports:
      - "5432:5432"
    volumes:
      - ./dbData:/var/lib/mysql